-- CreateTable
CREATE TABLE "PricingSettings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "companyName" TEXT NOT NULL DEFAULT 'Man and Van',
    "rating" DOUBLE PRECISION NOT NULL DEFAULT 4.9,
    "reviewCount" INTEGER NOT NULL DEFAULT 0,
    "smallVanRate" DOUBLE PRECISION NOT NULL DEFAULT 25,
    "mediumVanRate" DOUBLE PRECISION NOT NULL DEFAULT 35,
    "largeVanRate" DOUBLE PRECISION NOT NULL DEFAULT 45,
    "lutonVanRate" DOUBLE PRECISION NOT NULL DEFAULT 55,
    "helper2Rate" DOUBLE PRECISION NOT NULL DEFAULT 12,
    "helper3Rate" DOUBLE PRECISION NOT NULL DEFAULT 24,
    "stairRate" DOUBLE PRECISION NOT NULL DEFAULT 5,
    "stopRate" DOUBLE PRECISION NOT NULL DEFAULT 10,
    "minHours" DOUBLE PRECISION NOT NULL DEFAULT 5,
    "maxHours" DOUBLE PRECISION NOT NULL DEFAULT 17.5,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PricingSettings_pkey" PRIMARY KEY ("id")
);
